src/ground/grain-server/webapp/blueprints/data.py
import time
import json
import os
import random

from flask import Blueprint, jsonify, request, current_app, send_file

from ...common import definitions as common_definitions
from ..redis_store import redis_store


def now():
    return float(round(time.time()*1000))


def viewlimit(plotname, timebase=now()):
    return timebase - current_app.config["%s_PLOT_SCOPE_MS" % plotname].total_seconds()*1000


data = Blueprint('data', __name__, url_prefix="/data")


@data.route("/plot_data")
def plot_data():
    chart_name = request.args.get("chartName")

    if chart_name == "acc":
        return _get_acc_data()
    elif chart_name == "gyro":
        return _get_gyro_data()
    elif chart_name == "temperature":
        return _get_temperature_data()
    elif chart_name == "pressure":
        return _get_pressure_data()



@data.route("/map_data")
def map_data():
    # Достаем элементы
    time = now()
    latest_update_time = float(request.args.get("latestUpdateTime"))
    latest_update_time = max(latest_update_time, viewlimit("MAP", time))

    zsetname = common_definitions.ZSET_NAME_MAP
    elems = redis_store.zrangebyscore(zsetname, latest_update_time, time, withscores=True, score_cast_func=int)

    data = []
    for e in elems:
        value, score = e
        value = json.loads(value.decode("utf-8"))
        data.append({
            'time_usec': value['time_usec'],
            'fix_type': value['fix_type'],
            'lat': value['lat'] / (10.0 ** 7),
            'lon': value['lon'] / (10.0 ** 7),
            'alt': value['alt'] / 1000,
            'servertime': score
        })

    return jsonify(data)


@data.route("/gl_data")
def gl_data():
    # Достаем последний элемент
    zsetname = common_definitions.ZSET_NAME_ATTITUDE
    elems = redis_store.zrange(zsetname, -1, -1, withscores=True, score_cast_func=int)

    data = []
    for e in elems:
        value, score = e
        value = json.loads(value.decode("utf-8"))
        data.append({
            'data': [value['q2'], value['q3'], value['q4'], value['q1']],
            'servertime': score
        })

    if not data:
        data.append({
            'data': [1, 0, 0, 0],
            'servertime': -1
        })

    return jsonify(data)


@data.route("/spectrum_data")
def spectrum_data():
    # Достаем последний элемент
    zsetname = common_definitions.ZSET_NAME_SPECTRUM

    try:
        spectrum, score = redis_store.zrange(zsetname, -1, -1, withscores=True, score_cast_func=int) [0]
        spectrum = json.loads(spectrum.decode("utf-8"))

        data = {'data': [], 'identifier': spectrum['identifier']}

        for i, dot in enumerate(spectrum['data']):
            data['data'].append({
                'x': i,
                'y': dot
            })

        data['timestamp'] = score

    except IndexError:
        data = {'data': [], 'identifier': -1}

    return jsonify(data)


@data.route("/spectrum_img")
def spectrum_img():
    identifier = int(request.args.get("identifier"))

    if identifier == -1:
        return send_file('static/staytuned.jpg')

    return send_file('tmp/img/%d.png' % identifier)


@data.route("/background")
def background_img():
    backgrounds_folder = os.path.join(current_app.root_path, "static/backgrounds/")
    background = random.choice(os.listdir(backgrounds_folder))

    responce = send_file("static/backgrounds/" + background)
    responce.headers._list[3] = ('Cache-Control','no-cache')
    return responce

@data.route("/status")
def status():
    # Достаем последний элемент
    zsetname = common_definitions.ZSET_NAME_STATE

    try:
        status, score = redis_store.zrange(zsetname, -1, -1, withscores=True, score_cast_func=int) [0]
        status = json.loads(status.decode("utf-8"))

    except IndexError:
        status = {"status": -1}

    return jsonify(status)


def _get_data_abstract(plotname, yvalue_name, time=now()):
    """ Преобразует набор "мавлинкоджсоновых элементов в набор элементов точек для графика
    Элементы оси Y выбираются по указанному ключу """

    # Достаем элементы
    latest_update_time = float(request.args.get("latestUpdateTime"))
    latest_update_time = max(latest_update_time, viewlimit(plotname, time))

    zsetname = getattr(common_definitions, "ZSET_NAME_%s" % plotname)
    elems = redis_store.zrangebyscore(zsetname, latest_update_time, time, withscores=True, score_cast_func=int)

    data = []
    for e in elems:
        value, score = e
        value = json.loads(value.decode("utf-8"))
        data.append({
            "x": value["time_boot_ms"] / 1000.0,  # будем показывать секунды, считаем что бортовое время в мс
            "y": value[yvalue_name],
            "servertime": score
        })

    return data


def _get_acc_data():
    """ Датасет для графика акселерометра """
    time = now()
    datax, datay, dataz = [_get_data_abstract("IMU", x, time) for x in ("xacc", "yacc", "zacc")]

    for x, y, z in zip(datax, datay, dataz):
        x["y"] /= 1000.0
        y["y"] /= 1000.0
        z["y"] /= 1000.0

    latestUpdateTime = request.args.get("latestUpdateTime")
    if len(datax) > 0:
        latestUpdateTime = datax[-1]["servertime"]

    data = {
        "datas": [datax, datay, dataz],
        "latestUpdateTime": latestUpdateTime,
        "viewlimit": viewlimit("IMU", time)
    }

    return jsonify(data)


def _get_gyro_data():
    """ Датасет для графика гироскопа """
    time = now()
    datax, datay, dataz = [_get_data_abstract("IMU", x, time) for x in ("xgyro", "ygyro", "zgyro")]

    latestUpdateTime = request.args.get("latestUpdateTime")
    if len(datax) > 0:
        latestUpdateTime = datax[-1]["servertime"]

    for x, y, z in zip(datax, datay, dataz):
        x["y"] /= 1000.0
        y["y"] /= 1000.0
        z["y"] /= 1000.0

    data = {
        "datas": [datax, datay, dataz],
        "latestUpdateTime": latestUpdateTime,
        "viewlimit": viewlimit("IMU", time)
    }

    return jsonify(data)


def _get_temperature_data():
    time = now()
    temperature_int = _get_data_abstract("PRESSTEMP_INTERNAL", "temperature", time)
    temperature_ext = _get_data_abstract("PRESSTEMP_EXTERNAL", "temperature", time)

    latestUpdateTime = request.args.get("latestUpdateTime")
    if len(temperature_int) > 0:
        latestUpdateTime = temperature_int[-1]["servertime"]


    for record in temperature_int:
        record["y"] /= 100.0

    data = {
        "datas": [temperature_int, temperature_ext],
        "latestUpdateTime": latestUpdateTime,
        "viewlimit": viewlimit("PRESSTEMP", time)
    }

    return jsonify(data)

def _get_pressure_data():
    time = now()
    pressure_int = _get_data_abstract("PRESSTEMP_INTERNAL", "press_abs", time)
    pressure_ext = _get_data_abstract("PRESSTEMP_EXTERNAL", "press_abs", time)

    latestUpdateTime = request.args.get("latestUpdateTime")
    if len(pressure_int) > 0:
        latestUpdateTime = pressure_int[-1]["servertime"]

    data = {
        "datas": [pressure_int, pressure_ext],
        "latestUpdateTime": latestUpdateTime,
        "viewlimit": viewlimit("PRESSTEMP", time)
    }

    return jsonify(data)

src/ground/grain-server/webapp/blueprints/gl_test.py
from flask import Blueprint, render_template, abort, jsonify, request, current_app
from jinja2 import TemplateNotFound


gl_test = Blueprint('gl_test', __name__, url_prefix="/gl_test")


@gl_test.route('/')
def gl_test_index():
    try:
        return render_template('gl_test.html')
    except TemplateNotFound:
        abort(404)


src/ground/grain-server/webapp/templates/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Grain MCC for Bombus</title>

    {% block styles %}
    {% assets "bs_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}"/>
    {% endassets %}
    {% assets "main_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}"/>
    {% endassets %}

    <style>
        #header {
            margin-top:10px;
        }

        .margin-bottom {
            margin-bottom:20px;
        }

        #footer {
            border-top-style:double;
            border-width: 3px;
        }
    </style>
    {% endblock %}


</head>
<body>
<nav class="navbar navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="/">
        <img src="/static/Bombus.gif" style="max-height:40px" href="/" alt="BOMBUS">
        MISSION CONTROL CENTRE
    </a>

    {% block navbared %}
    {% endblock %}

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
                <a class="nav-link" href="/overview">Overview</a>
                <a class="nav-link" href="/plots">Plots</a>
            </li>

            <div id="login_form">
                <form name="login" action="">
                  <fieldset>
                    <label for="totpcode" id="totpcode_label">TOTP code</label>
                    <input type="text" name="totpcode" id="totpcode" size="30" value="" class="text-input" />
                    <label class="error" for="totpcode" id="name_error">This field is required.</label>

                    <br />
                    <input type="submit" name="submit" class="button" id="submit_btn" value="Send" />
                  </fieldset>
                </form>
            </div>
        </ul>
    </div>

</nav>

<img src="{{ url_for("data.background_img") }}" style="position:fixed; width:100%; height:auto;">

<div class="container-fluid min-height-100vh under-header whitebg">
    {% block content %}{% endblock %}

    <div id="footer" class="row" style="text-align:right">
        <div class="col">
            <p>Shostakovichs SCF. 2019.</p>
            <p>Vasilly.Prokopyev, Antonloh, Arina, Kirs67, SeresHotes</p>
            <p><a href="https://github.com/shostakovichs-spacecraft-factory/">Team github</a></p>
        </div>
    </div>
</div>


{% block js %}
{% assets "jq_js" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% assets "bs_js" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% endblock %}

</body>
</html>





src/ground/grain-server/webapp/templates/landing.html
{% extends "basic.html" %}

{% block content %}
    <div class="row h-100 center-block">
        <div class="col-xl-12 text-center" id="header">
            <h1>EHLO EVERYONE</h1>
        </div>
    </div>
{% endblock %}

src/ground/grain-server/webapp/templates/overview.html
{% extends "basic.html" %}

{% block styles %}
{{ super() }}

{% assets "openlayers_css" %}
<link rel="stylesheet" href="{{ ASSET_URL }}"/>
{% endassets %}

<style>

    .three-js-scene {
        min-height: 70vh;
        height: 70vh;
    }

</style>

{% endblock %}



{% block navbared %}

<div id="status-div" style="color: white; font-size: 30px;">No-state</div>

{% endblock %}



{% block content %}
    <div class="row h-100 center-block">
        <div class="col-xl-12 text-center" id="header">
            <h1>OVERVIEW</h1>
        </div>
    </div>

    <div class="row h-100 center-block margin-bottom">
        <div class="col-sm-6 col-md-4 col-lg-3 text-center">
            <canvas id="acc-plot-canvas"></canvas>
        </div>

        <div class="col-sm-6 col-md-4 col-lg-3 text-center">
            <canvas id="gyro-plot-canvas"></canvas>
        </div>

        <div class="col-sm-6 col-md-4 col-lg-3 text-center">
            <canvas id="temperature-plot-canvas"></canvas>
        </div>

        <div class="col-sm-6 col-md-4 col-lg-3 text-center">
            <canvas id="pressure-plot-canvas"></canvas>
        </div>
    </div>

    <div class="row h-100 center-block margin-bottom">
        <div class="col-sm-6 col-md-6 text-center" style="display: flex; align-items: center;">
            <img id="spectrum-img" src="{{ url_for("data.spectrum_img") }}?identifier=-1" alt="Stay tuned!" class="img-fluid text-center"/>
        </div>
        <div class="col-sm-6 col-md-6 text-center">
            <canvas id="spectrum-plot-canvas"></canvas>
        </div>
    </div>

    <div class="row h-50 center-block margin-bottom">
        <div class="col-sm-6 col-md-6 text-center">
            <div class="h-100 center-block three-js-scene" id="orientation-model-scene"></div>
        </div>
        <div class="col-sm-6 col-md-6 text-center">
            <div class="h-100 center-block" id="map"></div>
        </div>
    </div>

    <div style="display: none;">
        <div id="popup" title="Telemetry"></div>
    </div>

{% endblock %}




{% block js %}

{% assets "popper_js" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{{ super() }}

{% assets "chart_js" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% assets "mcc_charts" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}


{% assets "openlayers_js" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% assets "mcc_map" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}


{% assets "three" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% assets "three_stl_loader" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% assets "mcc_gl" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}


{% assets "mcc_spectrum" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}


{% assets "mcc_status" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}


<script type="text/javascript">


$(document).ready(function(){
    var charts = [{
        name: "acc",
        datasets:
        [
            {
                "label": "Ускорения по X (g)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#f44242",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
            {
                "label": "Ускорения по Y (g)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#15ff00",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
            {
                "label": "Ускорения по Z (g)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#001dff",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
        ]
    },{
        name: "gyro",
        datasets:
        [
            {
                "label": "Угловая скорость по X (deg/s)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#f44242",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
            {
                "label": "Угловая скорость по Y (deg/s)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#15ff00",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
            {
                "label": "Угловая скорость по Z (deg/s)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#001dff",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },

        ]
    },{
        name: "temperature",
        datasets:
        [
            {
                "label": "Внутренняя температура (BMP280) (degC)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#15ff00",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
            {
                "label": "Внешняя температура (DS18B20) (degC)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#f44242",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
        ]
    },{
        name: "pressure",
        datasets:
        [
            {
                "label": "Внутреннее давление (BMP280) (hPa)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#15ff00",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
            {
                "label": "Внешнее давление (DS18B20) (hPa)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#f44242",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
        ]
    }];

    updatePeriodMs = {{ config["PLOT_DATA_UPDATE_PERIOD_MS"] }}
    updatePeriodGLMs = {{ config["MODEL_DATA_UPDATE_PERIOD_MS"] }}
    updatePeriodSpectrumMs = {{ config["SPECTRUM_DATA_UPDATE_PERIOD_MS"] }}
    updatePeriodStatusMs = {{ config["STATUS_DATA_UPDATE_PERIOD_MS"] }}

    plotDataUrl = "{{ url_for("data.plot_data") }}"
    mapDataUrl = "{{ url_for("data.map_data") }}"
    glDataUrl = "{{ url_for("data.gl_data") }}"
    spectrumDataUrl = "{{ url_for("data.spectrum_data") }}"
    spectrumIMGUrl = "{{ url_for("data.spectrum_img") }}"
    statusUrl = "{{ url_for("data.status") }}"

    mccChartsMain(charts, updatePeriodMs, plotDataUrl );
    mccMapMain(mapDataUrl);
    mccGLMain($("#orientation-model-scene"), "{{ url_for('static', filename='cansat.stl') }}", glDataUrl);
    mccSpectrumMain(spectrumDataUrl, spectrumIMGUrl);
    mccStatusMain(statusUrl);
})

</script>
{% endblock %}

src/ground/grain-server/webapp/templates/overview_old.html
{% extends "basic.html" %}

{% block styles %}
{{ super() }}

{% assets "openlayers_css" %}
<link rel="stylesheet" href="{{ ASSET_URL }}"/>
{% endassets %}

<style>

    .three-js-scene {
        min-height: 70vh;
        height: 70vh;
    }

</style>

{% endblock %}



{% block navbared %}

<div id="status-div" style="color: white; font-size: 30px;">No-state</div>

<audio controls>
    <source src="/sound" type="audio/wav">
    Your browser does not support the audio tag.
</audio>


{% endblock %}



{% block content %}
    <div class="row h-100 center-block">
        <div class="col-xl-12 text-center" id="header">
            <h1>OVERVIEW</h1>
        </div>
    </div>

    <div class="row h-100 center-block margin-bottom">
        <div class="col-xl-6 text-center">
            <canvas id="acc-plot-canvas"></canvas>
        </div>

        <div class="col-xl-6 text-center">
            <canvas id="gyro-plot-canvas"></canvas>
        </div>

        <div class="col-xl-6 text-center">
            <canvas id="temperature-bmp-plot-canvas"></canvas>
        </div>

        <div class="col-xl-6 text-center">
            <canvas id="temperature-am-plot-canvas"></canvas>
        </div>

        <div class="col-xl-6 text-center">
            <canvas id="pressure-plot-canvas"></canvas>
        </div>

        <div class="col-xl-6 text-center">
            <canvas id="distance-plot-canvas"></canvas>
        </div>

        <div class="col-xl-6 text-center">
            <canvas id="humidity-plot-canvas"></canvas>
        </div>

        <div class="col-xl-6 text-center">
            <canvas id="luminosity-plot-canvas"></canvas>
        </div>
    </div>

    <div class="row h-100 center-block margin-bottom">
        <div class="col-xl-6 text-center">
            <img id="spectrum-img" src="{{ url_for("data.spectrum_img") }}" alt="Stay tuned!" style="max-height:300px"/>
        </div>
        <div class="col-xl-6 text-center">
            <canvas id="spectrum-plot-canvas"></canvas>
        </div>
    </div>

    <div class="row h-100 center-block margin-bottom">
        <div class="col-xl-6 text-center">
            <div class="h-100 center-block three-js-scene" id="orientation-model-scene"></div>
        </div>
        <div class="col-xl-6 text-center">
            <div class="h-100 center-block" id="map"></div>
        </div>
    </div>

    <div style="display: none;">
        <div id="popup" title="Telemetry"></div>
    </div>

{% endblock %}




{% block js %}

{% assets "popper_js" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{{ super() }}

{% assets "chart_js" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% assets "mcc_charts" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}


{% assets "openlayers_js" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% assets "mcc_map" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}


{% assets "three" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% assets "three_stl_loader" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% assets "mcc_gl" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}


{% assets "mcc_spectrum" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}


{% assets "mcc_status" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}


<script type="text/javascript">


$(document).ready(function(){
    var charts = [{
        name: "acc",
        datasets:
        [
            {
                "label": "Ускорения по X (g)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#f44242",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
            {
                "label": "Ускорения по Y (g)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#15ff00",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
            {
                "label": "Ускорения по Z (g)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#001dff",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
        ]
    },{
        name: "gyro",
        datasets:
        [
            {
                "label": "Угловая скорость по X (deg/s)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#f44242",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
            {
                "label": "Угловая скорость по Y (deg/s)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#15ff00",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
            {
                "label": "Угловая скорость по Z (deg/s)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#001dff",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },

        ]
    },{
        name: "temperature-bmp",
        datasets:
        [
            {
                "label": "Температура по датчику BMP280 (degC)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#f44242",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
        ]
    },{
        name: "temperature-am",
        datasets:
        [
            {
                "label": "Температура по датчику AM2320 (degC)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#15ff00",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
        ]
    },{
        name: "pressure",
        datasets:
        [
            {
                "label": "Давление по датчику BMP280 (hPa)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#15ff00",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
        ]
    },{
        name: "distance",
        datasets:
        [
            {
                "label": "Дистанция до поверхности (cm)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#15ff00",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
        ]
    },{
        name: "humidity",
        datasets:
        [
            {
                "label": "Относительная влажность воздуха (%)",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#15ff00",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
        ]
    },{
        name: "luminosity",
        datasets:
        [
            {
                "label": "Освещённость",
                "fill": false,
                "pointRadius": 0,
                "borderColor": "#15ff00",
                "borderWidth": 2,
                "lineTension": 0,
                "data": [],
            },
        ]
    }];

    updatePeriodMs = {{ config["PLOT_DATA_UPDATE_PERIOD_MS"] }}
    updatePeriodGLMs = {{ config["MODEL_DATA_UPDATE_PERIOD_MS"] }}
    updatePeriodSpectrumMs = {{ config["SPECTRUM_DATA_UPDATE_PERIOD_MS"] }}
    updatePeriodStatusMs = {{ config["STATUS_DATA_UPDATE_PERIOD_MS"] }}

    plotDataUrl = "{{ url_for("data.plot_data") }}"
    mapDataUrl = "{{ url_for("data.map_data") }}"
    glDataUrl = "{{ url_for("data.gl_data") }}"
    spectrumDataUrl = "{{ url_for("data.spectrum_data") }}"
    spectrumIMGUrl = "{{ url_for("data.spectrum_img") }}"
    statusUrl = "{{ url_for("data.status") }}"

    mccChartsMain(charts, updatePeriodMs, plotDataUrl );
    mccMapMain(mapDataUrl);
    mccGLMain($("#orientation-model-scene"), "{{ url_for('static', filename='cansat.stl') }}", glDataUrl);
    mccSpectrumMain(spectrumDataUrl, spectrumIMGUrl);
    mccStatusMain(statusUrl);
})

</script>
{% endblock %}